spring:
  application:
    name: 'KirillTestBot'
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create

  # H2 settings
  h2:
    console:
      enabled: true
      path: /h2
      show-sql: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:mem:public
    username: sa
    password:
    driver-class-name: org.h2.Driver

bot:
  name: 'KirillTestBot'
  token: 'xxx'
  menu:
    start: 'Получить приветственное сообщение'
    data: 'Получить информацию о подписке'
    freeze: 'Заморозить подписку'
    help: 'Информация как использовать этого бота'
    settings: 'Установите ваши предпочтения'