default.datasource:
  url: ${DATABASE_URL:jdbc:h2:mem:public};DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=true;MODE=PostgreSQL
  username: ${DATABASE_USER:sa}
  password: ${DATABASE_PASSWORD:}
  driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hikari:
    connection-timeout: 3000
    minimum-idle: 1
    maximum-pool-size: 10
    idle-timeout: 10000
    max-lifetime: 60000

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:KirillTestBot}
  datasource:
    url: ${default.datasource.url}
    username: ${default.datasource.username}
    password: ${default.datasource.password}
    driver-class-name: ${default.datasource.driver-class-name}
    hikari:
      jdbc-url: ${default.datasource.url}
      username: ${default.datasource.username}
      password: ${default.datasource.password}
      driver-class-name: ${default.datasource.driver-class-name}
      connection-timeout: ${default.datasource.hikari.connection-timeout}
      minimum-idle: ${default.datasource.hikari.minimum-idle}
      maximum-pool-size: ${default.datasource.hikari.maximum-pool-size}
      idle-timeout: ${default.datasource.hikari.idle-timeout}
      max-lifetime: ${default.datasource.hikari.max-lifetime}
      pool-name: "default-bot"
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non_contextual_creation: true
        time_zone: UTC
    show-sql: false
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:/db/migration
    user: ${default.datasource.username}
    password: ${default.datasource.password}
    schemas: ${DATABASE_SCHEMA:public}
    out-of-order: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

bot:
  name: 'KirillTestBot'
  token: 'xxx'
  menu:
    start: 'Получить приветственное сообщение'
    data: 'Получить информацию о подписке'
    freeze: 'Заморозить подписку'
    help: 'Информация как использовать этого бота'
    settings: 'Установите ваши предпочтения'