server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bot_db?currentSchema=bot_db
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:/db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: ${DATABASE_SCHEMA:bot_db}
    out-of-order: true

bot:
  name: 'KirillTestBot'
  token: 'XXX'
  menu:
    start: 'Запустить бота'
    data: 'Получить информацию о подписке'
    stop: 'Отписаться от бота'
    help: 'Информация как использовать этого бота'
    subscribe: "Оформить подписку"