version: "3.7"

services:
  postgres:
    image: 'postgres:17'
    container_name: 'postgres_db'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=sa'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=bot_db'